export enum GbpSubMenusPathEnum {
    LAYERS = "camadas",
    LAYERS_GROUPS = "grupo-camadas",
    LAYERS_STYLES = "estilos-camadas",
    ACESSO_WEBGEO = "acessos-webgeo",
    USERS = "usuarios",
    ROLES = "grupos",
    LOGS = "logs",
    DASHBOARD = "",
    ACESSO_GRP = "acessos-grp",
    LIST_GOALS = "list-goals",
    STEPS = "steps",
    SECRETARIES = "secretaries",
    SIMPLE = "simplificado",
    COMPLETE = "completo",
    NEW = "novo",
    RETURN = "resposta",
}

export enum GbpModulesPathEnum {
    GRP = "grp-config",
    WEBGEO = "webgeo",
    PROJECTS = "projetos",
    GOV_PLAN = "plano_governo",
    HOME = "",
    AGENDA = "agenda",
    REGISTER = "cadastro",
    SEARCH = "consulta",
    GBP = "gbp",
    CONTACTS = "contatos",
    REPORTS = "relatorios",
}

export enum GbpMenusPathEnum {
    GBP_REGISTER_POLITICAL_CHAIN = "registro-corrente-politica",
    GBP_REGISTER_OFICIO = "registro-oficio",
    GBP_REGISTER_EMENDA = "registro-emenda",
    GBP_REGISTER_APPOINTMENT = "registro-compromisso",
    GBP_REGISTER_PF = "registro-pf",
    GBP_REGISTER_PJ = "registro-pj",
    CONFIG_WEBGEO = "config_webgeo",
    WEBGEO_ACCESS = "webgeo_access",
    WEBGEO_LOGS = "webgeo_logs",
    GRP_ACCESS = "grp_access",
    GRP_LOGS = "grp_logs",
    GOV_GOALS = "gov_goals",
}
